sudo: required

services:
  - docker

script:
  - docker pull node:4
  - docker build -t kenjones/nodejs:4 -f Dockerfile.base .
  - docker build -t kenjones/nodejs-mocha -f Dockerfile.mocha .
  - docker build -t kenjones/nodejs-dev -f Dockerfile.dev .
  - docker tag kenjones/nodejs-dev kenjones/nodejs:4-dev
  - docker build -t kenjones/nodejs:4-slim -f Dockerfile.slim .
  - docker build -t kenjones/nodejs:4-slim-onbuild -f Dockerfile.slim-onbuild .
  - docker pull alpine:3.3
  - docker build -t nodejs-alpine:4 -f Dockerfile.node-alpine .
  - docker build -t kenjones/nodejs:4-alpine -f Dockerfile.base-alpine .
  - docker build -t kenjones/nodejs:4-dev-alpine -f Dockerfile.dev-alpine .
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push kenjones/nodejs:4
  - docker push kenjones/nodejs-mocha
  - docker push kenjones/nodejs-dev
  - docker push kenjones/nodejs:4-dev
  - docker push kenjones/nodejs:4-slim
  - docker push kenjones/nodejs:4-slim-onbuild
  - docker push kenjones/nodejs:4-alpine
  - docker push kenjones/nodejs:4-dev-alpine
